[package]
name = "goblin_bunker_jam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_flycam = "0.9.0"
bevy_obj = "0.9.1"
